version: '3.9'

services:
  web1:
    image: nginx:alpine
    container_name: web1
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./html/web1/web1.html:/usr/share/nginx/html/index.html
  web2:
      image: nginx:alpine
      container_name: web2
      restart: always
      ports:
        - 8081:80
      volumes:
        - ./html/web2/web2.html:/usr/share/nginx/html/index.html
  web3:
      image: nginx:alpine
      container_name: web3
      restart: always
      ports:
        - 8082:80
      volumes:
        - ./html/web3/web3.html:/usr/share/nginx/html/index.html
  nginx:
    image: nginx:alpine
    restart: always
    ports:
    - 80:80
    volumes:
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    environment:
      NGINX_LOG_LEVEL: DEBUG
